version: '3.8'

services:
  auth-api:
    container_name: auth-api
    build: .
    command: yarn run start:dev
    environment:
      - TYPEORM_HOST=postgres
    volumes:
      - ./src:/app/src
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
